### ISSUE TITLE
Swift module error

### ISSUE THREAD

**Issue by RodolfoAntonici** [Orchextra/orchextra-ios-sdk#18]
I'm trying to import the Orchextra v2.1.7 into my project, but I've got the following error:

> module compiled with Swift 3.1 cannot be imported in Swift 3.2

Tried on a clean project, didn't work either.

**Comment by cmvicentehe** [comment]
I have just published a new release with framework compiled using Swift 3.2. Could you check it out again and tell us if your issue has been fixed?

**Comment by RodolfoAntonici** [comment]
It worked, thank you very much!
By the way, I think it would be a good idea to update the sample app.

**Comment by cmvicentehe** [comment]
You are right. I have just updated the sample app and compiled it using xCode9. If everything is right from your side, we are going to close this issue ok? Thank you so mucho for your feedback.
